### ISSUE TITLE
Support for Consuming Other Repositories

### ISSUE THREAD

**Issue by ericrobskyhuntley** [bplmaps/lane-mead-portal#23]
can only consume digitalcommonwealth repository - need support for e.g., Internet Archive

**Comment by garrettdashnelson** [comment]
You'll see that I have rather clumsily included the ability to include images and titles card items from Internet Archive (ie. line 37 in clientLoadingItemCard), but the main item page does not do anything with IA yet. My suggestion would be for IA items, rather than executing an IIIF and metadata fetch, as we do with DC objects, to instead just use IA's own `iframe` embedding functionality. 

For example, <https://lane-mead-portal-dev.netlify.app/item/ia--lanemeadbostonma1957lane/> would show the IA book viewer embed, which is:

```
<iframe src="https://archive.org/embed/lanemeadbostonma1957lane" width="560" height="384" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
```

**Comment by ericrobskyhuntley** [comment]
Consolidated `item-dc.astro` and `item-ia.astro` into one, implemented <iframe.../> embedding and Internet Archive Metadata call. [de9b4ee](https://github.com/bplmaps/lane-mead-portal/commit/de9b4eeeba8d84db3a1e89ff43930a1bde281659)
